### PR TITLE
General code enhancements

### LINKED ISSUE #5: separate files
each agent has a specific file that needs to be run in order to visualize it.
instead of having one file that runs all of them.

### LINKED ISSUE #8: requirements.txt bug
Libraries need to be version specific. Right now the libraries and the versions are in the file.

### PR DESCRIPTION
**Pull request by Owen-Dechow**
- [x] I read the [README](https://github.com/YaadR/Visualizing_RL/blob/main/README.md) file 
- [x]  I have checked that the code is compiling and working
- [x]  I have added appropriate comments in-between the code for better understanding of the algorithm
- [x]  I have checked for potential bug my code might create in other parts of the project
- [x] Add a visual example of the changes you made if possible

Changes:
* Added windows support
* Removed unused imports
* Cleaned up commented code
* Add directory management system `Visualizing_RL\Ver1\path.py`
* Added main.py file to run all agents out of `Visualizing_RL\Ver1\main.py`
* Fixed `requirements.txt`
* Updated `README.md`
* Formatted code to pep8 using black
* Added `.gitattributes` to standardize line endings
* Fixed window not responding error
* Added support for when close button selected on pygame window
* Update `.gitignore`

closes #8, closes #5 

terminal

### CODE REVIEW

**Review by YaadR — APPROVED** [review]
Great work! 👌🏽
I'll go over it shortly, and hopefully merge it by the weekend.

**Comment by YaadR** [comment]
@Owen-Dechow  
We are waiting for the final approval of the entire project before we merge your pull request. This might take a while. 
Thank you for your patience.

**Comment by Owen-Dechow** [comment]
@YaadR
Hi, I am working on archiving/deleting old forks/repos and was deciding if I wanted to archive or delete my fork for this PR. If you still intend to merge this PR could you let me know so I do not delete it.

**Comment by YaadR** [comment]
@Owen-Dechow 
Thank you

**Pull request merged**
